#!/bin/bash
# DSpark acceptance sweep on ik_llama.cpp: one server load per draft FILE, every n_max and every
# prompt inside that load (n_max is a per-request override, "speculative.n_max").
#   arms (ARMS):  tl37    corrected target layers, no causal key -> ik defaults to a causal block mask
#                 tl37nc  same file with dflash.attention.causal=false (the reference block is bidirectional)
# Acceptance does not depend on machine load; tok/s does, so load average is logged next to every row.
# Coordination: /tmp/cpu-busy.flag tells a CPU benchmark running alongside to hold its timing runs.
# The serving process is stopped first and restarted by the EXIT trap, even on failure.
# Do not edit this file while it runs: bash reads scripts incrementally.
set -u
export GGML_CUDA_NO_PINNED=1
source <(sed -n "/^M=/p; /^OT=/p; /^liq()/p" ~/engine-ab.sh)
IK=$HOME/ik_llama.cpp/build/bin/llama-server
DIR=/models/DeepSeek-V4.1-Flash-DSpark
declare -A DRAFT=([tl37]=$DIR/DeepSeek-V4.1-Flash-Fp8-128x742M-MXFP4_MOE.tl37.gguf
                  [tl37nc]=$DIR/DeepSeek-V4.1-Flash-Fp8-128x742M-MXFP4_MOE.tl37nc.gguf)
ARMS=${ARMS:-"tl37 tl37nc"}
NMAXES=${NMAXES:-"5 3"}
NPRED=${NPRED:-200}
OUT=${OUT:-/tmp/dspark-sweep.jsonl}
PORT=8099
SP=""
say() { echo "$(date +%T) $*"; }

finish() {
  [ -n "$SP" ] && kill -0 "$SP" 2>/dev/null && { kill "$SP"; while kill -0 "$SP" 2>/dev/null; do sleep 2; done; }
  if ! curl -sf 127.0.0.1:8001/health >/dev/null; then
    nohup bash ~/rig-log-v41-serve.sh > /tmp/llm-serve.log 2>&1 < /dev/null &
    for i in $(seq 1 180); do curl -sf 127.0.0.1:8001/health >/dev/null && { say "8001 back"; break; }; sleep 5; done
  fi
  rm -f /tmp/cpu-busy.flag
  say SWEEP_DONE
}
trap finish EXIT

PROMPTS=/tmp/dspark-sweep-prompts.json
python3 - "$PROMPTS" <<'PY'
import json, sys
p = [
 "Write a Python function that merges two sorted lists into one sorted list, with a short docstring.",
 "Explain how TCP's three-way handshake works, step by step.",
 "Translate into Korean: The meeting has been moved to Thursday because the projector is broken.",
 "Solve and show your work: a train travels 180 km in 2.5 hours. What is its average speed in m/s?",
 "Write a C function that reverses a singly linked list in place.",
 "Summarize the causes of the French Revolution in one paragraph.",
 "List ten common Linux commands and what each one does.",
 "Write a haiku sequence of three poems about autumn rain.",
 "Extract every date from this text as ISO 8601: 'We met on March 3rd 2021, again on 12/05/2022, and finally on the first of June, 2023.'",
 "What is the difference between a process and a thread? Answer for a beginner.",
 "Write a SQL query that returns the top five customers by total order value, given tables customers(id, name) and orders(id, customer_id, amount).",
 "한국의 사계절을 초등학생에게 설명하는 짧은 글을 써 줘.",
 "Prove that the square root of 2 is irrational.",
 "Write a bash script that finds the ten largest files under the current directory.",
 "Describe the water cycle, naming each stage.",
 "Give a recipe for a simple tomato pasta sauce with quantities.",
 "Write a JavaScript debounce function and explain when to use it.",
 "Compare REST and GraphQL in a short table-like list of pros and cons.",
 "Continue this story for two paragraphs: The lighthouse keeper found a letter that had not been there the night before.",
 "Convert this JSON to YAML: {\"name\": \"rig\", \"gpus\": [\"3090\", \"4090\"], \"ram_gb\": 251, \"serve\": {\"port\": 8001, \"threads\": 32}}",
]
json.dump(p, open(sys.argv[1], "w"))
PY

touch /tmp/cpu-busy.flag
while pgrep -x llama-bench >/dev/null; do say "waiting for a running llama-bench to finish"; sleep 15; done
for pid in $(pgrep -x llama-server); do say "stopping llama-server $pid"; kill "$pid"; while kill -0 "$pid" 2>/dev/null; do sleep 2; done; done

run_arm() {  # $1 arm
  local arm=$1 d=${DRAFT[$1]}
  [ -f "$d" ] || { say "$arm: missing $d"; return 1; }
  local t0=$(date +%s)
  $IK -m "$M" -c 16384 -ngl 99 -t 32 -b 2048 -ub 2048 -ot "$OT" --host 127.0.0.1 --port $PORT \
      --model-draft "$d" --spec-type "dspark:n_max=5" > "/tmp/dspark-sweep-srv-$arm.log" 2>&1 &
  SP=$!
  local ready=""
  for i in $(seq 1 240); do
    kill -0 $SP 2>/dev/null || { say "$arm died"; grep -iE "error|fail|assert" "/tmp/dspark-sweep-srv-$arm.log" | tail -5; SP=""; return 1; }
    if grep -qE "HTTP server listening|listening on http|server is listening|main loop" "/tmp/dspark-sweep-srv-$arm.log" && curl -sf 127.0.0.1:$PORT/health >/dev/null; then ready=1; break; fi
    sleep 5
  done
  [ -n "$ready" ] || { say "$arm never ready"; return 1; }
  say "$arm up pid $SP after $(( $(date +%s) - t0 )) s"
  grep -E "draft flavor|causal" "/tmp/dspark-sweep-srv-$arm.log" | head -3 | sed 's/^/  /'
  curl -s 127.0.0.1:$PORT/completion -d '{"prompt":"hi","n_predict":4,"temperature":0}' >/dev/null
  for nmax in $NMAXES; do
    python3 - "$arm" "$nmax" "$PROMPTS" "$NPRED" "$PORT" "$OUT" <<'PY'
import json, sys, urllib.request, os
arm, nmax, prompts, npred, port, out = sys.argv[1], int(sys.argv[2]), sys.argv[3], int(sys.argv[4]), sys.argv[5], sys.argv[6]
tot_d = tot_a = 0
for i, p in enumerate(json.load(open(prompts)), 1):
    body = {"prompt": "<｜User｜>" + p + "<｜Assistant｜></think>", "n_predict": npred, "temperature": 0,
            "cache_prompt": False, "speculative.n_max": nmax}
    req = urllib.request.Request(f"http://127.0.0.1:{port}/completion", json.dumps(body).encode(), {"Content-Type": "application/json"})
    r = json.load(urllib.request.urlopen(req, timeout=900))
    t = r.get("timings", {})
    dn, da = t.get("draft_n", 0), t.get("draft_n_accepted", 0)
    tot_d += dn; tot_a += da
    row = {"arm": arm, "n_max": nmax, "prompt": i, "draft_n": dn, "accepted": da,
           "decode_n": t.get("predicted_n"), "tps": round(t.get("predicted_per_second", 0), 2),
           "load1": float(open("/proc/loadavg").read().split()[0])}
    open(out, "a").write(json.dumps(row) + "\n")
    open(f"/tmp/dspark-sweep-text-{arm}-n{nmax}-{i}.txt", "w").write(r.get("content", ""))
    print("  %s n_max=%d #%02d: decode %s @ %.2f tok/s | draft %d acc %d (%.0f%%) | load %.1f" % (
        arm, nmax, i, row["decode_n"], row["tps"], dn, da, 100.0 * da / dn if dn else 0, row["load1"]), flush=True)
print("  == %s n_max=%d total: draft %d accepted %d (%.1f%%)" % (arm, nmax, tot_d, tot_a, 100.0 * tot_a / tot_d if tot_d else 0), flush=True)
PY
  done
  kill $SP; while kill -0 $SP 2>/dev/null; do sleep 2; done; SP=""; say "$arm stopped"
}

for arm in $ARMS; do run_arm "$arm"; done

echo "== text identity across arms (same binary, greedy; a difference is batched-vs-single drift or a broken switch)"
set -- $ARMS
if [ $# -ge 2 ]; then for nmax in $NMAXES; do for i in $(seq 1 20); do
  cmp -s "/tmp/dspark-sweep-text-$1-n$nmax-$i.txt" "/tmp/dspark-sweep-text-$2-n$nmax-$i.txt" || echo "  n_max=$nmax #$i differs"
done; done; fi
